# db:
#     image: postgres:9.4
#     environment:
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_USER=postgres
#     ports:
#         - "5432:5432"
worker:
    build: .
    command: python main.py
    volumes:
        - .:/src
        - ./sql:/opt/flyway-3.2.1/sql
    # links:
    #     - db        